routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('adminlte');
});

Route::group(['middleware'=>'web'],function(){
	Route::auth();
});
Route::group(['middleware'=>['web','auth']], function(){
	Route::get('/home', 'HomeController@index');
	Route::get('/',function(){
		if(Auth::user()){
			return view('mahasiswa_calon.adminlte');
		}else{
			return view('home1');
		}
	});
});


	Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    Route::get('mahasiswa_calonEdit/{id}',['as' => 'mahasiswa_calonEdit', 'uses' => 'mahasiswa_calonController@edit']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);
    Route::get('facultiesEdit/{id}',['as' => 'facultiesEdit', 'uses' => 'facultiesController@edit']);

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);
    Route::get('majorsEdit/',['as' => 'majorsEdit', 'uses' => 'major\majorController@edit']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);
    Route::get('departmentsEdit/{id}',['as' => 'departmentsEdit', 'uses' => 'departments\departmentsController@edit']);

Route::resource('portal','portalController');


Route::resource('mahasiswalulusan', 'mahasiswalulusan\mahasiswalulusanController');
 Route::get('mahasiswalulusanIndex/',['as' => 'mahasiswalulusanIndex', 'uses' => 'mahasiswalulusan\mahasiswalulusanController@index']);


/*  Lecturer Standar 4   */
Route::resource('lecturers','Akreditasi\Lecturer\StandartController');

/* Penelitian Standar 7 */
Route::resource('lecturerResearch', 'Akreditasi\LecturerResearch\StandartResearchController');

app/mahasiswa_calon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class mahasiswa_calon extends Model
{
    protected $table = 'mahasiswa_calon';

}

app/Http/Controllers/mahasiswa_calonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\mahasiswa_calon;
use App\Http\Requests;
use App\majors;
use App\academic_years;
use App\kota_kabupaten;
use App\Http\Requests\mahasiswa_calon\UpdateRequest;
use App\Http\Requests\mahasiswa_calon\StoreRequest;
use Datatables;

class mahasiswa_calonController extends Controller
{
    public function index()
    {   
        
    	$mahasiswa_calon=mahasiswa_calon::all();
        return view('mahasiswa_calon.mahasiswa_calonView',compact('mahasiswa_calon'));
    }

    public function getmahasiswa_calon()
    {
        $mahasiswa_calon = mahasiswa_calon::select(['program_studi_id','tahun_ajaran_id','nama','telp','email','tempat_lahir','gender','alamat_asal','jalur_pendaftaran','reguler','hasil_seleksi'])->get();
  
        return Datatables::of($mahasiswa_calon)->make(true);
    }
    public function create()
    {
        $majors=majors::all();
        $kota_kabupaten=kota_kabupaten::all();
        $academics=academic_years::all();
        return view('mahasiswa_calon.mahasiswa_calonCreate',compact('kota_kabupaten','academics','majors'));
        //
    }
    public function store(StoreRequest $request)
    {
        $mahasiswa_calon = new mahasiswa_calon();
        $mahasiswa_calon->program_studi_id = $request->program_studi_id;
        $mahasiswa_calon->tahun_ajaran_id=$request->tahun_ajaran_id;
        $mahasiswa_calon->nama=$request->nama;
        $mahasiswa_calon->telp=$request->telp;
        $mahasiswa_calon->email=$request->email;
        $mahasiswa_calon->tempat_lahir=$request->tempat_lahir;
        $mahasiswa_calon->gender=$request->gender;
        $mahasiswa_calon->alamat_asal=$request->alamat_asal;
        $mahasiswa_calon->jalur_pendaftaran=$request->jalur_pendaftaran;
        $mahasiswa_calon->reguler=$request->reguler;
        $mahasiswa_calon->hasil_seleksi=$request->hasil_seleksi;
        $mahasiswa_calon->save();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function destroy($id)
    {
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        $mahasiswa_calon->delete();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
    public function edit($id)
    {
        $majors=majors::all();
        $academics=academic_years::all();
        $kota_kabupaten=kota_kabupaten::all();
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        return view('mahasiswa_calon.mahasiswa_calonEdit', compact('academics','kota_kabupaten','majors','mahasiswa_calon'));
    }
    public function update(UpdateRequest $request, $id)
    {
        $mahasiswa_calon = mahasiswa_calon::findOrFail($id);
        $mahasiswa_calon->program_studi_id = $request->program_studi_id;
        $mahasiswa_calon->tahun_ajaran_id=$request->tahun_ajaran_id;
        $mahasiswa_calon->nama=$request->nama;
        $mahasiswa_calon->telp=$request->telp;
        $mahasiswa_calon->email=$request->email;
        $mahasiswa_calon->tempat_lahir=$request->tempat_lahir;
        $mahasiswa_calon->gender=$request->gender;
        $mahasiswa_calon->alamat_asal=$request->alamat_asal;
        $mahasiswa_calon->jalur_pendaftaran=$request->jalur_pendaftaran;
        $mahasiswa_calon->reguler=$request->reguler;
        $mahasiswa_calon->hasil_seleksi=$request->hasil_seleksi;
        $mahasiswa_calon->save();
        return redirect()->route('mahasiswa_calons.index')->with('alert-success', 'Data Successfully Updated.');
    }
}

resources/views/mahasiswa_calon/adminlte.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    @include('layouts.header')
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      @include('layouts.sidebar')
    </section>
    <!-- /.sidebar -->
  </aside>

 <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">
            @yield('content')
            </section><!-- /.content -->
        </div>
        @yield('scripts')
  
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.11
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="bootstrap/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="plugins/sparkline/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/app.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
</body>
</html>

resources/views/mahasiswa_calon/mahasiswa_calonCreate.blade.php
@extends('mahasiswa_calon.adminlte')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>Tambah Mahasiwa</b></h4>
                    <hr>
            <form action="{{route('mahasiswa_calons.store')}}" method="post">
                    {{csrf_field()}}
                    <label class="w3-label w3-text-green"><b>Program Studi ID</b></label>
                        <div class="form-group{{ $errors->has('program_studi_id') ? ' has-error' : '' }}">
                        <select class="form-control m-bot15" name="program_studi_id">
                            @if($majors->count() > 0)
                            @foreach($majors as $major)
                            <option value="{{$major->id}}">{{$major->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                    </div>
                    <label class="w3-label w3-text-green"><b>Tahun Ajaran ID</b></label>
                        <div class="form-group{{ $errors->has('tahun_ajaran_id') ? ' has-error' : '' }}">
                           <!-- <input type="text" name="tahun_ajaran_id" class="form-control" placeholder="tahun_ajaran_id" required>
                            {!! $errors->first('tahun_ajaran_id', '<p class="help-block">:message</p>') !!}-->
                            <select class="form-control m-bot15" name="tahun_ajaran_id">
                            @if($academics->count() > 0)
                            @foreach($academics as $major)
                            <option value="{{$major->id}}">{{$major->name}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        <label class="w3-label w3-text-green"><b>nama</b></label>
                        <div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
                            <input type="text" name="nama" class="form-control" placeholder="nama" required>
                        
                            {!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                        <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="text" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Tempat Lahir</b></label>
                        <div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="tempat_lahir">
                            @if($kota_kabupaten->count() > 0)
                            @foreach($kota_kabupaten as $kota)
                            <option value="{{$kota->id}}">{{$kota->nama_kota_kabupaten}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        <label class="w3-label w3-text-green"><b>Gender</b></label>
                        <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                            <input type="text" name="gender" class="form-control" placeholder="gender" required>
                        
                            {!! $errors->first('gender', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Alamat Asal</b></label>
                        <div class="form-group{{ $errors->has('alamat_asal') ? ' has-error' : '' }}">
                            <input type="text" name="alamat_asal" class="form-control" placeholder="alamat_asal" required>
                        
                            {!! $errors->first('alamat_asal', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Jalur Pendaftaran</b></label>
                        <div class="form-group{{ $errors->has('jalur_pendaftaran') ? ' has-error' : '' }}">
                            <input type="text" name="jalur_pendaftaran" class="form-control" placeholder="jalur_pendaftaran" required>
                        
                            {!! $errors->first('jalur_pendaftaran', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Reguler</b></label>
                        <div class="form-group{{ $errors->has('reguler') ? ' has-error' : '' }}">
                            <input type="text" name="reguler" class="form-control" placeholder="reguler" required>
                        
                            {!! $errors->first('reguler', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Hasil Seleksi</b></label>
                        <div class="form-group{{ $errors->has('hasil_seleksi') ? ' has-error' : '' }}">
                            <input type="text" name="hasil_seleksi" class="form-control" placeholder="hasil_seleksis" required>
                        
                            {!! $errors->first('hasil_seleksi', '<p class="help-block">:message</p>') !!}
                        </div>
                            <input type="submit" class="btn btn-primary" value="Simpan">
                    

                    </form>
        </div>
    </div>
       
@endsection

resources/views/mahasiswa_calon/mahasiswa_calonEdit.blade.php
@extends('mahasiswa_calon.adminlte')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('mahasiswa_calons.update', $mahasiswa_calon->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Program Studi ID</b></label>
						<div class="form-group{{ $errors->has('program_studi_id') ? ' has-error' : '' }}">
							
					<select class="form-control m-bot15" name="program_studi_id">
                            @foreach($majors as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->program_studi_id)
                            selected
                            @endif
                            >
                            {{$major->name}}
                        </option>
                            @endForeach
                           
                        </select>

						</div>

						<label class="w3-label w3-text-green"><b>Tahun Ajaran ID</b></label>
						<div class="form-group{{ $errors->has('tahun_ajaran_id') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="tahun_ajaran_id">
                            @foreach($academics as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->tahun_ajaran_id)
                            selected
                            @endif
                            >
                            {{$major->name}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('tahun_ajaran_id', '<p class="help-block">:message</p>') !!}
						</div>

						<label class="w3-label w3-text-green"><b>Nama</b></label>
						<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
							<input type="text" name="nama" class="form-control" placeholder="nama" value="{{$mahasiswa_calon->nama}}" required>
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>

						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$mahasiswa_calon->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$mahasiswa_calon->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Tempat Lahir</b></label>
						<div class="form-group{{ $errors->has('tempat_lahir') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="tempat_lahir">
                            @foreach($kota_kabupaten as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $mahasiswa_calon->tempat_lahir)
                            selected
                            @endif
                            >
                            {{$major->nama_kota_kabupaten}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('tempat_lahir', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Gender</b></label>
						<div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
							<input type="text" name="gender" class="form-control" placeholder="Gender" value="{{$mahasiswa_calon->gender}}" required>
							{!! $errors->first('gender', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Alamat Asal</b></label>
						<div class="form-group{{ $errors->has('alamat_asal') ? ' has-error' : '' }}">
							<input type="text" name="alamat_asal" class="form-control" placeholder="Alamat Asal" value="{{$mahasiswa_calon->alamat_asal}}" required>
							{!! $errors->first('alamat_asal', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Jalur Pendaftaran</b></label>
						<div class="form-group{{ $errors->has('jalur_pendaftaran') ? ' has-error' : '' }}">
							<input type="text" name="jalur_pendaftaran" class="form-control" placeholder="Jalur Pendaftaran" value="{{$mahasiswa_calon->jalur_pendaftaran}}" required>
							{!! $errors->first('jalur_pendaftaran', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Reguler</b></label>
						<div class="form-group{{ $errors->has('reguler') ? ' has-error' : '' }}">
							<input type="text" name="reguler" class="form-control" placeholder="Reguler" value="{{$mahasiswa_calon->reguler}}" required>
							{!! $errors->first('reguler', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Hasil Seleksi</b></label>
						<div class="form-group{{ $errors->has('hasil_seleksi') ? ' has-error' : '' }}">
							<input type="text" name="hasil_seleksi" class="form-control" placeholder="Hasil Seleksi" value="{{$mahasiswa_calon->hasil_seleksi}}" required>
							{!! $errors->first('hasil_seleksi', '<p class="help-block">:message</p>') !!}
						</div>
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('mahasiswa_calons.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/mahasiswa_calon/mahasiswa_calonView.blade.php
@extends('mahasiswa_calon.adminlte')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Mahasiswa </h3>   
    <a href="{{route('mahasiswa_calonCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Program Studi</td>
                <td>Tahun Ajaran</td>
                <td>Nama</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Tempat Lahir</td>
                <td>Gender</td>
                <td>Alamat Asal</td>
                <td>Jalur Pendaftaran</td>
                <td>Reguler</td>
                <td>Hasil Seleksi</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($mahasiswa_calon as $mahasiswa_calon)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$mahasiswa_calon->program_studi_id}}</td>
                            <td>{{$mahasiswa_calon->tahun_ajaran_id}}</td>
                            <td>{{$mahasiswa_calon->nama}}</td>
                            <td>{{$mahasiswa_calon->telp}}</td>
                            <td>{{$mahasiswa_calon->email}}</td> 
                            <td>{{$mahasiswa_calon->tempat_lahir}}</td>
                            <td>{{$mahasiswa_calon->gender}}</td>  
                            <td>{{$mahasiswa_calon->alamat_asal}}</td>
                            <td>{{$mahasiswa_calon->jalur_pendaftaran}}</td> 
                            <td>{{$mahasiswa_calon->reguler}}</td> 
                            <td>{{$mahasiswa_calon->hasil_seleksi}}</td>   
                            <td><form method="POST" action="{{ route('mahasiswa_calons.destroy', $mahasiswa_calon->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{route('mahasiswa_calonEdit', $mahasiswa_calon->id)}}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>

                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection
<!--@push('js')
@section('scripts') 
<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable(
        {
         "scrollX": true,
             processing: true,
                serverSide: true,
                //
                ajax: '{{ url("get-mahasiswa_calon") }}',   
        });
} );
 </script>

@endsection
@endpush
 
<!--@push('js')
<script type="text/javascript">
    $(function(){
        $("#data-mahasiswa_calon").DataTable({
            "scrollX": true,
             processing: true,
                serverSide: true,
                //
                ajax: '{{ url("get-mahasiswa_calon") }}',
                columns: [
                    { data: 'program_studi_id', name: 'program_studi_id' },
                    { data: 'tahun_ajaran_id', name: 'tahun_ajaran_id' },
                    { data: 'nama', name: 'nama' },
                    { data: 'telp', name: 'telp' },
                    { data: 'email', name: 'email' },
                    { data: 'tempat_lahir', name: 'tempat_lahir' },
                    { data: 'gender', name: 'gender' },
                    { data: 'alamat_asal', name: 'alamat_asal' },
                    { data: 'jalur_pendaftaran', name: 'jalur_pendaftaran' },
                    { data: 'reguler', name: 'reguler' },
                    { data: 'hasil_seleksi', name: 'hasil_seleksi' },

                ]

        });
    });
</script>

@endpush -->