routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('adminlte');
});

Route::group(['middleware'=>'web'],function(){
	Route::auth();
});
Route::group(['middleware'=>['web','auth']], function(){
	Route::get('/home', 'HomeController@index');
	Route::get('/',function(){
		if(Auth::user()){
			return view('mahasiswa_calon.adminlte');
		}else{
			return view('home1');
		}
	});
});


	Route::resource('mahasiswa_calons', 'mahasiswa_calonController');
    Route::get('mahasiswa_calon/',['as' => 'mahasiswa_calon', 'uses' => 'mahasiswa_calonController@index']);
    Route::get('mahasiswa_calonCreate/',['as' => 'mahasiswa_calonCreate', 'uses' => 'mahasiswa_calonController@create']);
    Route::get('mahasiswa_calonEdit/{id}',['as' => 'mahasiswa_calonEdit', 'uses' => 'mahasiswa_calonController@edit']);

    Route::resource('faculties', 'faculties\facultiesController');
    Route::get('facultiesIndex/',['as' => 'facultiesIndex', 'uses' => 'faculties\facultiesController@index']);
    Route::get('facultiesCreate/',['as' => 'facultiesCreate', 'uses' => 'faculties\facultiesController@create']);
    Route::get('facultiesEdit/{id}',['as' => 'facultiesEdit', 'uses' => 'facultiesController@edit']);

    Route::resource('majors', 'major\majorController');
    Route::get('majorsIndex/',['as' => 'majorsIndex', 'uses' => 'major\majorController@index']);
    Route::get('majorsCreate/',['as' => 'majorsCreate', 'uses' => 'major\majorController@create']);
    Route::get('majorsEdit/',['as' => 'majorsEdit', 'uses' => 'major\majorController@edit']);

    Route::resource('departments', 'departments\departmentsController');
    Route::get('departmentsIndex/',['as' => 'departmentsIndex', 'uses' => 'departments\departmentsController@index']);
    Route::get('departmentsCreate/',['as' => 'departmentsCreate', 'uses' => 'departments\departmentsController@create']);
    Route::get('departmentsEdit/{id}',['as' => 'departmentsEdit', 'uses' => 'departments\departmentsController@edit']);

Route::resource('portal','portalController');


Route::resource('mahasiswalulusan', 'mahasiswalulusan\mahasiswalulusanController');
 Route::get('mahasiswalulusanIndex/',['as' => 'mahasiswalulusanIndex', 'uses' => 'mahasiswalulusan\mahasiswalulusanController@index']);


/*  Lecturer Standar 4   */
Route::resource('lecturers','Akreditasi\Lecturer\StandartController');

/* Penelitian Standar 7 */
Route::resource('lecturerResearch', 'Akreditasi\LecturerResearch\StandartResearchController');

app/Http/Controllers/faculties/facultiesController.php
<?php

namespace App\Http\Controllers\faculties;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\faculties;
use App\kota_kabupaten;

class facultiesController extends Controller
{
    public function index()
    {   
        
    	$faculties=faculties::all();
        return view('faculties.facultiesView',compact('faculties'));
    }
    public function create()
    {
    	$kota_kabupaten=kota_kabupaten::all();
        return view('faculties.facultiesCreate',compact('kota_kabupaten'));
    }
    public function store(Request $request)
    {
        $faculties = new faculties();
        $faculties->name=$request->name;
        $faculties->university=$request->university;
        $faculties->telp=$request->telp;
        $faculties->email=$request->email;
        $faculties->founded_on=$request->founded_on;
        $faculties->city=$request->city;
        $faculties->save();
        return redirect()->route('faculties.index')->with('alert-success','Data berhasil Disimpan.');
    }
    public function edit($id)
    {
        $kota_kabupaten=kota_kabupaten::all();
        $faculties = faculties::findOrFail($id);
        return view('faculties.facultiesEdit', compact('kota_kabupaten','faculties'));
    }
    public function update(Request $request, $id)
    {
        $faculties = faculties::findOrFail($id);
        $faculties->name=$request->name;
        $faculties->university=$request->university;
        $faculties->telp=$request->telp;
        $faculties->email=$request->email;
        $faculties->founded_on=$request->founded_on;
        $faculties->city=$request->city;
        $faculties->save();
        return redirect()->route('faculties.index')->with('alert-success', 'Data Successfully Updated.');
    }
    public function destroy($id)
    {
        $faculties = faculties::findOrFail($id);
        $faculties->delete();
        return redirect()->route('faculties.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }
}

resources/views/faculties/adminlte.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('layouts.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    @include('layouts.header')
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      @include('faculties.sidebar')
    </section>
    <!-- /.sidebar -->
  </aside>

 <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <section class="content">
            @yield('content')
            </section><!-- /.content -->
        </div>
        @yield('scripts')
  
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.11
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.6 -->
<script src="bootstrap/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="plugins/sparkline/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
<script src="plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/app.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
</body>
</html>

resources/views/faculties/facultiesCreate.blade.php
@extends('faculties.adminlte')

@section('content')
<div class="container-fluid">
    
                <div class="panel-body">
                <br style="clear:both">
                    <h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>Tambah Fakultas</b></h4>
                    <hr>
            <form action="{{route('faculties.store')}}" method="post">
                    {{csrf_field()}}
                        <label class="w3-label w3-text-green"><b>name</b></label>
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <input type="text" name="name" class="form-control" placeholder="name" required>
                        
                            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>University</b></label>
                        <div class="form-group{{ $errors->has('university') ? ' has-error' : '' }}">
                            <input type="text" name="university" class="form-control" placeholder="university" required>
                        
                            {!! $errors->first('university', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Telp</b></label>
                            <div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
                            <input type="telp" name="telp" class="form-control" placeholder="telp" required>
                        
                            {!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
                        </div>
                        
                        <label class="w3-label w3-text-green"><b>Email</b></label>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <input type="email" name="email" class="form-control" placeholder="email" required>
                        
                            {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>Founded On</b></label>
                        <div class="form-group{{ $errors->has('founded_on') ? ' has-error' : '' }}">
                            <input type="date" name="founded_on" class="form-control" placeholder="founded_on" required>
                        
                            {!! $errors->first('founded_on', '<p class="help-block">:message</p>') !!}
                        </div>
                        <label class="w3-label w3-text-green"><b>City</b></label>
                        <div class="form-group{{ $errors->has('homepage') ? ' has-error' : '' }}">
                            <select class="form-control m-bot15" name="city">
                            @if($kota_kabupaten->count() > 0)
                            @foreach($kota_kabupaten as $kota)
                            <option value="{{$kota->id}}">{{$kota->nama_kota_kabupaten}}</option>
                            @endForeach
                            @else
                            No Record Found
                            @endif   
                        </select>
                        </div>
                        
                            <input type="submit" class="btn btn-primary" value="Simpan">
                       

                    </form>
         </div>
     </div>

        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/faculties/facultiesEdit.blade.php
@extends('faculties.adminlte')
@section('content')
<div class="container-fluid">
	
				<div class="panel-body">
				<br style="clear:both">
					<h4 class="w3-label w3-text-green" style="margin-bottom: 25px; text-align: center;"><b>EDIT JOBLIST</b></h4>
                    <hr>
					<form action="{{route('faculties.update',$faculties->id)}}" method="post">
					<input name="_method" type="hidden" value="PATCH">
					{{csrf_field()}}
						<label class="w3-label w3-text-green"><b>Nama</b></label>
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<input type="text" name="name" class="form-control" placeholder="name" value="{{$faculties->name}}" required>
							{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>University</b></label>
						<div class="form-group{{ $errors->has('university') ? ' has-error' : '' }}">
							<input type="text" name="university" class="form-control" placeholder="Jalur Pendaftaran" value="{{$faculties->university}}" required>
							{!! $errors->first('university', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Telp</b></label>
						<div class="form-group{{ $errors->has('telp') ? ' has-error' : '' }}">
							<input type="text" name="telp" class="form-control" placeholder="Telp" value="{{$faculties->telp}}" required>
							{!! $errors->first('telp', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Email</b></label>
						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<input type="email" name="email" class="form-control" placeholder="Email" value="{{$faculties->email}}" required>
							{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
						</div>
						<label class="w3-label w3-text-green"><b>Founded On</b></label>
						<div class="form-group{{ $errors->has('founded_on') ? ' has-error' : '' }}">
							<input type="date" name="founded_on" class="form-control" placeholder="Alamat Asal" value="{{$faculties->founded_on}}" required>
							{!! $errors->first('founded_on', '<p class="help-block">:message</p>') !!}
						</div>
						
						<label class="w3-label w3-text-green"><b>City</b></label>
						<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
							<select class="form-control m-bot15" name="city">
                            @foreach($kota_kabupaten as $major)
                            <option 
                            value="{{$major->id}}"
                            @if($major->id === $faculties->city)
                            selected
                            @endif
                            >
                            {{$major->nama_kota_kabupaten}}
                        </option>
                            @endForeach
                           
                        </select>
							{!! $errors->first('city', '<p class="help-block">:message</p>') !!}
						</div>
						
						<div class="form-group">
							<button type="submit" class="btn button btn-primary pull-right"><span class="glyphicon glyphicon-pencil">Edit</span></button>

							<a href="{{route('faculties.index')}}" class="btn button  btn-primary pull-left"><span class="glyphicon glyphicon-arrow-left"></span></a>
						</div>
					</form>
				
		
	</div>
</div>
@endsection

resources/views/faculties/facultiesView.blade.php
@extends('faculties.adminlte')
 
@section('content')
<div class="row">
<div class="col-md-8 col-md-offset-2">
    <h3 align="center">Data Calon Mahasiswa </h3>   
    <a href="{{route('facultiesCreate')}}" class="btn btn-primary btn-md" ><span  class="glyphicon glyphicon-list-alt"></span>  Add New</a></a>  
    <div>
        <h3> </h3>
    </div>
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <td>No</td>
                <td>Name</td>
                <td>University</td>
                <td>Telp</td>
                <td>Email</td>
                <td>Founded On</td>
                <td>City</td>
                <td>Aksi</td>
                
            </tr>
        </thead>
        <tbody>
            <?php $no=1; ?>
                        @foreach($faculties as $data)
                            <tr class="">
                            <td>{{$no++}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->university}}</td>
                            <td>{{$data->telp}}</td> 
                            <td>{{$data->email}}</td>
                            <td>{{$data->founded_on}}</td>  
                            <td>{{$data->city}}</td>   
                            <td><form method="POST" action="{{ route('faculties.destroy', $data->id) }}" accept-charset="UTF-8">
                                <input name="_method" type="hidden" value="DELETE">
                                <input name="_token" type="hidden" value="{{ csrf_token() }}">

                                <a href="{{ route('facultiesEdit', $data->id) }}" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>


                                <button type="submit" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="bottom" title="delete"><span class="glyphicon glyphicon-trash" onclick="return confirm('Anda yakin akan menghapus data ?');" ></span>
                                    </button>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection

resources/views/faculties/sidebar.blade.php
<section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Alexander Pierce</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class=""><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
            <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Layout Options</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">4</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
            <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
          </ul>
        </li>
       
       <!-- <li class="treeview">
          <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
            <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
            <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
          </ul>
        </li>-->
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tables</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="active treeview-menu">
            <li class="{{set_active('mahasiswa_calon')}} {{set_active('mahasiswa_calonCreate')}} {{set_active('mahasiswa_calonEdit')}}"><a href="{{route('mahasiswa_calon')}}"><i class="fa fa-circle-o"></i> Mahasiswa Calon</a></li>

            <li class="{{set_active('facultiesIndex')}} {{set_active('facultiesCreate')}} {{set_active('facultiesEdit')}}"><a href="{{route('facultiesIndex')}}"><i class="fa fa-circle-o"></i>Fakultas</a></li>

            <li class="{{set_active('majorsIndex')}} {{set_active('majorCreate')}} {{set_active('majorsEdit')}}"><a href="{{route('majorsIndex')}}"><i class="fa fa-circle-o"></i> Majors</a></li>

            <li class="{{set_active('departmentsIndex')}} {{set_active('departmentsCreate')}} {{set_active('departmentEdit')}}"><a href="{{route('departmentsIndex')}}"><i class="fa fa-circle-o"></i> Departments</a></li>
          </ul>
        </li>
      <!--  <li>
          <a href="pages/calendar.html">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">3</small>
              <small class="label pull-right bg-blue">17</small>
            </span>
          </a>
        </li>
        <li>
          <a href="pages/mailbox/mailbox.html">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span>
          </a>
        </li>-->
       <!-- <li class="treeview">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
            <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
            <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
            <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
            <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
            <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
            <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
            <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
            <li><a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
          </ul>
        </li>-->
        <!--<li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li>
              <a href="#"><i class="fa fa-circle-o"></i> Level One
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                <li>
                  <a href="#"><i class="fa fa-circle-o"></i> Level Two
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          </ul>
        </li>-->
        <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
      </ul>
    </section>